### ISSUE TITLE
module 'pyparsing' has no attribute 'operatorPrecedence'

### ISSUE THREAD

**Issue by anandojha** [tekpinar/correlationplus#19]
correlationplus visualize -p nvt_run_1_solute.pdb -i nLMI.dat -o nLMI.png

outputs this error 

AttributeError: module 'pyparsing' has no attribute 'operatorPrecedence'

**Comment by anandojha** [comment]
Here is the output of the run_tests.py, you can see the error. Please help me resolve this. It seems to be a dependency error in your package
[run_tests.odt](https://github.com/tekpinar/correlationplus/files/7639081/run_tests.odt)
.

**Comment by anandojha** [comment]
So I can see here even if tests given here are failing!!

This is how I installed 

1. python -m venv corrPlusEnv
2. cd corrPlusEnv
3. source bin/activate
4. mkdir src
5. cd src
6. git clone https://github.com/tekpinar/correlationplus.git
7. cd correlationplus
8. pip install -U pip
9. pip install -e .

**Comment by tekpinar** [comment]
Can you send me nvt_run_1_solute.pdb and nLMI.dat files that you are using.

**Comment by anandojha** [comment]
I was using the test runs and i got the same error but Here are the links for the two files 

https://drive.google.com/file/d/1SarpvDDNQUCvOtEL0iquPe7TXacbT25Y/view?usp=sharing

https://drive.google.com/file/d/1um7Ap3pqFp2ARLc4CgdjaNNKhxh_BJfg/view?usp=sharing

**Comment by tekpinar** [comment]
Thanks for the files and reporting the bug. Now, it is corrected in the source file. If you reinstall it from the source, it should work (Please remove old virtual environment completely). 
For your particular case, I recommend using a single frame rather than an entire trajectory in pdb format. If you want to visualize the correlations with Pymol, multiframe pdb will cause a segmentation fault.

Just as a reference, I am writing the command I used to run your protein:
correlationplus visualize -i nLMI.dat -p nvt_run_1_solute_frame0.pdb -t nlmi -o nLMI-frame0 -d 10 -D 150 -v 0.75

Since you have a domain motion in your trajectory, I would also run it as follows:
correlationplus visualize -i nLMI.dat -p nvt_run_1_solute_frame999.pdb -t nlmi -o nLMI-frame999 -d 10 -D 150 -v 0.75 

The nLMI matrices are identical but how the correlations are projected onto the protein may change depending on the conformation. 

Best wishes,
Mustafa

**Comment by anandojha** [comment]
Thank you so much for the suggestions. I just figured it out that I made it to work by downgrading pyparsing but yeah I will install again.

**Comment by anandojha** [comment]
I am deleting the shared link since its public.
