### ISSUE TITLE
About the LMI equation (6) in your correlation_plus paper

### ISSUE THREAD

**Issue by TianmingQu** [tekpinar/correlationplus#22]
Hi, I read the paper titled with "Extracting Dynamical Correlations and Identifying Key Residues for Allosteric Conmmunication in Proteins by _correlationplus_", I wonder where does the equation (6) comes from. It looks different from the general mutual information equation I learned before. Could you give me some explanations about it?

**Comment by TianmingQu** [comment]
Also, have you ever considered applying PCA into the correlation analysis?

**Comment by tekpinar** [comment]
Unfortunately, no because I don't have time for that. However, I'll happily accept if someone adds it. At the end of the day, this is a completely open source scientific project.

**Comment by TianmingQu** [comment]
<img width="626" alt="截屏2022-07-13 上午10 10 06" src="https://user-images.githubusercontent.com/70176970/178754653-af9c73df-69ff-407e-a784-9ac12f4d2752.png">


Thank you for your so quick reply! I got one last question, could you give me some help on how to interpret this fig?

**Comment by tekpinar** [comment]
I can only give some general comments since I don't know the features of your system. 

This seems like a typical distribution of normalized LMIs in an MD trajectory:

As expected, you have many short-distance (<20 correlations) nLMI values. They are due to short physical interaction distance and/or similar secondary structural elements. 
In addition, you have many long-distance (>20 upto 60) high correlations, which may indicate allosteric interactions. However, you have to be sure about the oligomeric state of your protein to conclude for sure if they are due to dynamics of the protein or short distances within the oligomeric state. 
You can further investigate these high-nLMI and long-distance values with 'correlationplus visualize' script and project them onto your protein. In this way, you can have a better sense on their potential/probable implications.
