### ISSUE TITLE
correlationplus paths

### ISSUE THREAD

**Issue by rupeshagarwal** [tekpinar/correlationplus#23]
Hi,

When using correlationplus paths, how can I just extract just the residues in the path. I get a tcl and pml file as the output at the end but the residues in those two files are different.  Also, if I am running correlationplus paths analysis with wild type and a mutant, how can I interpret the data if I see that the path differs between them?
Also, does the frequency/stride of trajectory affect the nLMI calculations?

**Comment by tekpinar** [comment]
When using correlationplus paths, how can I just extract just the residues in the path. I get a tcl and pml file as the output at the end but the residues in those two files are different. 
**You can extract the residues from the pml file with the following linux command, assuming that your pml file is paths-sourceA10-targetA41.pml:
grep "show spheres" paths-sourceA10-targetA41.pml

In fact, they are identical residues in both tcl and pml scripts. However, I use 'residue' keyword instead of 'resid'. 'residue' keyword in VMD is used for a zero-based-continuous index.  You will see the same amino acids on both files.** 

Also, if I am running correlationplus paths analysis with wild type and a mutant, how can I interpret the data if I see that the path differs between them?

**Interpretation of the path differences depends entirely on your biological problem.** 

Also, does the frequency/stride of trajectory affect the nLMI calculations?
**As far as I remember, yes. It can affect your output. Check the https://onlinelibrary.wiley.com/doi/10.1002/prot.20784 as well because they mention that issue in their paper.**
