### ISSUE TITLE
Difficulty with Installation

### ISSUE THREAD

**Issue by ocampbel** [tekpinar/correlationplus#24]
Hello,

I am interested in using correlationplus in performing calculations of dynamics correlations to understand more about the dimerization mechanism of a viral protein. I am following the video tutorial for installation, and ran into an error after submitting _pip install -e ._ to the command line in the src/correlationplus/ folder. It is related to building a wheel for prody. The full error message can be found in the attached file. I appreciate your help with this.

Thank you,
Toyin Campbell

[corrplus_error.txt](https://github.com/user-attachments/files/17835791/corrplus_error.txt)

**Comment by tekpinar** [comment]
I think the problem is due to missing developer tools on Mac. Can you try 'xcode-select --install' on your terminal?
Another option is to use conda for the installation. 
PS: If you are going to use a molecular dynamics trajectory for correlation calculations, you can use the colab file (https://github.com/tekpinar/correlationplus/blob/master/correlationplus.ipynb)  in this repository. You don't need to install anything.

**Comment by ocampbel** [comment]
Yes, I am going to perform the calculations with an MD trajctory. I am successfully able to use the colab file, thanks for pointing it out! I will move forward with this. I appreciate your help!

Best, Toyin

**Comment by tekpinar** [comment]
Hi,
I am glad that colab approach worked. 
Best,
Mustafa
